### ISSUE TITLE
Clean up user specification in the memberserv.yaml

### ISSUE THREAD

**Issue by binhn** [hyperledger-archives/fabric#1752]
## Description

Even though the users specified in the `memberserv.yaml` are for testing purposes only (as a convenient method), the way it is laid out doesn't really follow wiper hierarchical format and difficult to read.

```
        users:
                # <EnrollmentID>: <system_role (1:client, 2: peer, 4: validator, 8: auditor)> <EnrollmentPWD> <Affiliation> <Affiliation_Role>
                lukas: 1 NPKYL39uKbkj bank_a    00001
```

It would be better to list the properties with key-value pairs. For example,

```
        user: lukas
                password: NPKYL39uKbkj 
                role: 1 
                affiliation: ACME    
                      title: 00001
        peer: 
```
