### ISSUE TITLE
[GoodFirstBug] Consolidate TLS (certfile,keyfile) YAML settings

### ISSUE THREAD

**Issue by JonathanLevi** [hyperledger-archives/fabric#1796]
## Description

Fabric uses `viper` for loading configurations from YAML files (sometimes also in combination of environment variables). Working on #1794 (changing some of these hard-coded string literals to constants), I just noticed that Fabric seems to expect:

`peer.tls.cert.file` and `peer.tls.key.file`  (in the `peer` configuration)
vs.
`server.tls.certfile` and `server.tls.keyfile`  (in the `membersrvc` configuration)
## Describe How to Resolve

While I don't have a strong opinion either way, these settings should be consolidated and be consistent.
## Good First Bug

I consider this a **Good First Bug** especially for those in the community who would like to pick up a simple coding task and get involved in fabric, build it, test it, and learn how to contribute to it. Need this done quickly and will be happy to spend some time guiding (pointing to the right Wiki's mostly ;-)), and verifying this all the way to submitting the PR [ usually at the modest tuition charge of 1-2 `MoreTests` digital currency ;-) ]

While this might seem like a relatively easy task, it does involve changing configurations, experiencing some peer/server failures (and recovery?), looking at logs and learning how both the `peer` and `membersrvc` processes are configured and set-up.

Interested? Hit me/us up here, or on [HL's Slack](http://hyperledgerproject.slack.com/jonathanlevi)

**Comment by GrapeBaBa** [comment]
@JonathanLevi I also can take this one😀

**Comment by JonathanLevi** [comment]
Go for it. Might be easier to update the `membersrvc` to match the other(s)... btw.

```
<joking>
    @GrapeBaBa: Leave something for the Hackathon!
</joking>
```

Happy coding!

**Comment by GrapeBaBa** [comment]
@JonathanLevi Please assign to me. I will start .

**Comment by GrapeBaBa** [comment]
@JonathanLevi 
After compare core.yaml and membersrvc.yaml, two questions
1. Per you suggestion, if updating the membersrvc to match core, I need change the root tag 'server' to 'peer', that means all the sub tag under server should all be changed. Is it OK?
https://github.com/hyperledger/fabric/blob/master/membersrvc/membersrvc.yaml#L3-L21
2. There are missing two tag 'enabled' and 'serverhostoverride' in membersrvc, does it need added?
https://github.com/hyperledger/fabric/blob/master/peer/core.yaml#L160-L167

**Comment by JonathanLevi** [comment]
Hi @GrapeBaBa. I was thinking about a much smaller change (mainly to change two entries in the YAML file), so it's not a full consolidation of the two files (passing the GoodFirstBug mark):

Effectively, just like `core.yaml` has an extra grouping of `peer.tls.cert.file`, that is:
https://github.com/hyperledger/fabric/blob/master/peer/core.yaml#L162-L165

```
    tls:
        enabled:  false
        cert:
            file: testdata/server1.pem
        key:
            file: testdata/server1.key
```

To have a similar level of hierarchy here:
https://github.com/hyperledger/fabric/blob/master/membersrvc/membersrvc.yaml#L18

So that instead of:

```
        # TLS certificate and key file paths
        tls:
               certfile: "/var/hyperledger/production/.membersrvc/tlsca.cert"
               keyfile: "/var/hyperledger/production/.membersrvc/tlsca.priv"
```

... in `membersrvc.yaml`, we will have:

```
        # TLS certificate and key file paths
        tls:
             cert:
                  file: "/var/hyperledger/production/.membersrvc/tlsca.cert"
             key:
                  file: "/var/hyperledger/production/.membersrvc/tlsca.priv"
```

(2) No, no need to add the `enabled` and `serverhostoverride` to the `membersrvc` end at this point. Thanks for checking!

**Comment by GrapeBaBa** [comment]
@JonathanLevi Got it. That is easy.

**Comment by JonathanLevi** [comment]
[GoodFirstBug] ;-)

**Comment by GrapeBaBa** [comment]
@JonathanLevi I found I need add environment variable in compose-defauls.yaml at line 14 to pass behave test. It is better to let #1810 first.
https://github.com/hyperledger/fabric/blob/master/bddtests/compose-defaults.yml#L14

BTW, I also think I can delete line 14 '- CORE_VM_ENDPOINT=http://172.17.0.1:2375' as I don't find any same config in membersrvc.yaml. Is that right?

**Comment by JonathanLevi** [comment]
Yes, agree on getting #1810 in first.

@jeffgarratt should know/confirm more about the CORE_VM_ENDPOINT under the `bddtests` dir...

**Comment by jeffgarratt** [comment]
@GrapeBaBa @JonathanLevi Core needs CORE_VM_ENDPOINT for docker services, which membersvcs does not need.

**Comment by JonathanLevi** [comment]
Fantastic! @jeffgarratt thanks for confirming.

**Comment by GrapeBaBa** [comment]
@jeffgarratt Now we have a problem with bddtests. If we uncomment the TLS config of membersrvc service(https://github.com/hyperledger/fabric/blob/master/membersrvc/membersrvc.yaml#L20-L21), serveral tests will failed. 

I try to fix the test by changing the compose-default.yaml like this, but not successful. Would you like help to give some clues?

``` yaml
vp:
  image: hyperledger/fabric-peer
  environment:
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_VM_ENDPOINT=http://172.17.0.1:2375
    # TODO:  This is currently required due to BUG in variant logic based upon log level.
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_PKI_TLS_ENABLED=true
    - CORE_PEER_PKI_TLS_ROOTCERT_FILE=./bddtests/tlsca.cert
    - CORE_PEER_PKI_TLS_SERVERHOSTOVERRIDE=OBC
  # Startup of peer must be delayed to allow membersrvc to come up first
  command: sh -c "sleep 5; peer node start"

membersrvc:
   image: hyperledger/fabric-membersrvc
   environment:
     - MEMBERSRVC_CA_SERVER_TLS_CERT_FILE=./bddtests/tlsca.cert
     - MEMBERSRVC_CA_SERVER_TLS_KEY_FILE=./bddtests/tlsca.priv
   command: membersrvc
```
