### ISSUE TITLE
grpc: ClientConn.resetTransport failed to create client transport: connection error

### ISSUE THREAD

**Issue by kamraanki** [hyperledger-archives/fabric#2320]
## Description

I have setup fabric dev network on my local. I have enabled TLS for the same. Peer could not be start facing following issues:-
![image](https://cloud.githubusercontent.com/assets/19260567/17133338/39adbd8c-5343-11e6-80d6-744b09d455b2.png)
## Describe How to Reproduce

Just configure membersrvc.yaml and core.yaml as below:-
### membersrvc.yaml

```
server:
        version: "0.1"
        gomaxprocs: -1
        rootpath: "/var/hyperledger/production"
        cadir: ".membersrvc"
        port: ":50051"
        tls:
            cert:
               file: "/opt/gopath/src/github.com/hyperledger/fabric/bddtests/tlsca.cert"
            key:
               file: "/opt/gopath/src/github.com/hyperledger/fabric/bddtests/tlsca.priv"
```
### core.yaml

```
  tls:
        enabled:  true
        cert:
            file: "./bddtests/tlsca.cert"
        key:
            file: "./bddtests/tlsca.priv"
        serverhostoverride: "OBC"
```

and running CA server as following:-

```
cd $GOPATH/src/github.com/hyperledger/fabric
make membersrvc && membersrvc
```

and peer with following command:-
`docker run --rm -it -e CORE_VM_ENDPOINT=http://172.17.0.1:2375 -e CORE_PEER_ID=vp0 -e CORE_PEER_ADDRESSAUTODETECT=true -e CORE_SECURITY_ENABLED=true -e CORE_SECURITY_PRIVACY=true -e CORE_PEER_PKI_ECA_PADDR=172.17.0.1:50051 -e CORE_PEER_PKI_TCA_PADDR=172.17.0.1:50051 -e CORE_PEER_PKI_TLSCA_PADDR=172.17.0.1:50051 -e CORE_SECURITY_ENROLLID=test_vp6 -e CORE_SECURITY_ENROLLSECRET=QiXJgHyV4t7A -e CORE_PEER_TLS_ENABLED=true -e CORE_PEER_TLS_SERVERHOSTOVERRIDE=OBC -e CORE_PEER_TLS_CERT_FILE=./bddtests/tlsca.cert -e CORE_PEER_TLS_KEY_FILE=./bddtests/tlsca.priv  hyperledger/fabric-peer peer node start`
