### ISSUE TITLE
[fabric 0.6.1-preview] running 4peers + CA on PBFT fails if we change PEER_ID

### ISSUE THREAD

**Issue by zamrokk** [hyperledger-archives/fabric#2408]
I have changed PEER_ID in the compose files, then I tried to run with PBFT.

While deploying a chaincode on **node1**, the nodes do not synchronized.
Here is the WARN message i see on logs :  

**node1**_1        | 08:56:35.018 [consensus/pbft] recvViewChange -> WARN 7eb Replica 0 found incorrect signature in view-change message: Could not verify message from **vp0** (unknown peer)

I do not have any **vp0** anymore in my config files. Actually, **node1** is the new name of **vp0**

If I run the network on NOOPS consensus , I have no problem

Here is the config of peer-secure-pbft-base.yaml :  
```
version: '2'
services:
  peer-secure-pbft-base:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CORE_PEER_DISCOVERY_PERIOD=60s
      - CORE_PEER_DISCOVERY_TOUCHPERIOD=61s
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
      - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
      - CORE_SECURITY_ENABLED=true
      - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=pbft 
      - CORE_PBFT_GENERAL_N=4
      - CORE_PBFT_GENERAL_K=1
      - CORE_PBFT_GENERAL_BATCHSIZE=1

    command: sh -c "sleep 10; peer node start"
```
and full-peer-ca.yaml :  

```
version: '2'
services:
  baseimage:
    build: ./baseimage
    image: hyperledger/fabric-baseimage:latest

  membersrvc:
    image: hyperledger/fabric-membersrvc:${ARCH_TAG}-0.6.1-preview
    extends:
      file: base/membersrvc.yaml
      service: membersrvc

  node1:
    image: hyperledger/fabric-peer:${ARCH_TAG}-0.6.1-preview
    extends:
      file: base/peer-secure-pbft-base.yaml
      service: peer-secure-pbft-base
    ports:
      - "7050:7050"
      - "7051:7051"
      - "7053:7053"
    environment:
      - CORE_PEER_ID=node1
      - CORE_SECURITY_ENROLLID=test_vp0
      - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
    links:
      - membersrvc
...
```
