### ISSUE TITLE
separete clients, peers and validators configuration in obcca.yaml

### ISSUE THREAD

**Issue by adecaro** [hyperledger-archives/fabric#590]
Because it seems that the configuration of the roles of the users in obcca.yaml generate some confusion, I would propose to move from this configuration style that we have now:

```
eca:
        users:
                lukas: 1 NPKYL39uKbkj
                system_chaincode_invoker: 2 DRJ20pEql15a
                diego: 2 DRJ23pEQl16a
                binhn: 3 7avZQLwcUe9q
                jim: 4 6avZQLwcUe9b
```

to the following that better differentiate between the different roles

```
eca:
        users:
                clients :
                    jim: 6avZQLwcUe9b
                    lukas: NPKYL39uKbkj

                peers: 
                    system_chaincode_invoker: DRJ20pEql15a
                    diego: DRJ23pEQl16a

                validators:
                    binhn: 7avZQLwcUe9q
```

@binhn, @elli-androulaki, @thkzrl: what do you think?
