### ISSUE TITLE
events src folder should be called "obc-events"

### ISSUE THREAD

**Issue by muralisrini** [hyperledger-archives/fabric#658]

**Comment by binhn** [comment]
the events is outside of openchain, but the config is currently defined in peer.validator:

```
        events:
            # The address that the Event service will be enabled on the validator
            address: 0.0.0.0:31315

            # total number of events that could be buffered without blocking the
            # validator sends
            buffersize: 100

            # milliseconds timeout for producer to send an event.
            # if < 0, if buffer full, unblocks immediately and not send
            # if 0, if buffer full, will block and guarantee the event will be sent out
            # if > 0, if buffer full, blocks till timeout
            timeout: 10
```

I think they should be outside of `peer`.
